### ISSUE TITLE
Change name in GSuite not supported

### ISSUE THREAD

**Issue by bramvandartel** [Inter-Actief/amelie#647]
Names in GSuite do not get changed, even though it is logged in the claudia timeline.

**Comment by Kurocon** [comment]
Should have been fixed recently: https://github.com/Inter-Actief/amelie/issues/570 but maybe google changed something again...

**Comment by bramvandartel** [comment]
Example that does not seem to be reflected in GSuite:
name: Fiasco AutoContactMomenten Test -> Fiasco Contactmoment

**Comment by bramvandartel** [comment]
Ah, caching of the account name in gmail is annoying. It seems to be updated at the correct spots, even though the name is still incorrect if you've ever sent an email to that mailaddress..
